name: Docker Scout SCA

on:
  workflow_dispatch:

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1) Login to Docker Hub with your Docker Hub account
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # e.g. "testuser731"
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # e.g. "dckr_pat_BGtOetE0AH6wDa9..."

      # 2) Pull the public image
      - name: Pull the image
        run: docker pull ancor87/welcome-to-docker

      # 3) Docker Scout scanning
      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare,sbom
          image: ancor87/welcome-to-docker
          exit-code: false
          sarif-file: sca_scout.sarif
          output: sbom_scout.spdx.json
          format: spdx

      # 4) Upload artifacts (SBOM, SARIF) and submit to GitHub code scanning
      - name: Upload SBOM file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom_scout.spdx.json
          path: sbom_scout.spdx.json

      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sca_scout.sarif
          path: sca_scout.sarif

      - name: Upload SARIF file to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca_scout.sarif
          category: Security/SCA

      - name: SBOM upload
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1
